// Generated by gencpp from file ired_msgs/Mode.msg
// DO NOT EDIT!


#ifndef IRED_MSGS_MESSAGE_MODE_H
#define IRED_MSGS_MESSAGE_MODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ired_msgs
{
template <class ContainerAllocator>
struct Mode_
{
  typedef Mode_<ContainerAllocator> Type;

  Mode_()
    : differential_wheel(false)  {
    }
  Mode_(const ContainerAllocator& _alloc)
    : differential_wheel(false)  {
  (void)_alloc;
    }



   typedef uint8_t _differential_wheel_type;
  _differential_wheel_type differential_wheel;





  typedef boost::shared_ptr< ::ired_msgs::Mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ired_msgs::Mode_<ContainerAllocator> const> ConstPtr;

}; // struct Mode_

typedef ::ired_msgs::Mode_<std::allocator<void> > Mode;

typedef boost::shared_ptr< ::ired_msgs::Mode > ModePtr;
typedef boost::shared_ptr< ::ired_msgs::Mode const> ModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ired_msgs::Mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ired_msgs::Mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ired_msgs::Mode_<ContainerAllocator1> & lhs, const ::ired_msgs::Mode_<ContainerAllocator2> & rhs)
{
  return lhs.differential_wheel == rhs.differential_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ired_msgs::Mode_<ContainerAllocator1> & lhs, const ::ired_msgs::Mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ired_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ired_msgs::Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ired_msgs::Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::Mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ired_msgs::Mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ired_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0f5377ca955b8c348e5de93be73c07e";
  }

  static const char* value(const ::ired_msgs::Mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0f5377ca955b8c3ULL;
  static const uint64_t static_value2 = 0x48e5de93be73c07eULL;
};

template<class ContainerAllocator>
struct DataType< ::ired_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ired_msgs/Mode";
  }

  static const char* value(const ::ired_msgs::Mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ired_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool differential_wheel\n"
;
  }

  static const char* value(const ::ired_msgs::Mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ired_msgs::Mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.differential_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ired_msgs::Mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ired_msgs::Mode_<ContainerAllocator>& v)
  {
    s << indent << "differential_wheel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.differential_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRED_MSGS_MESSAGE_MODE_H
